### ISSUE TITLE
URI resolver problem

### ISSUE THREAD

**Issue by mricaud** [jimetevenard/Maven-RelaxNG-Simplifier#1]
Hi @jimetevenard 
This is a really usefull project, thanks :) !

I have a schema `src/main/A.rng` that import `src/main/module/B.rng` with relativ path "module/B.rng"
When calling your plugin by building the pom (next to src) I get an error : Unable to load file /path/myproject/module/B.rng which doesn't exist.

I guess this is an URI resolver problem ?

**Comment by jimetevenard** [comment]
Hi @mricaud , I just solved this issue in Release 1.1.0
