### ISSUE TITLE
Adding jing as a dependency

### ISSUE THREAD

**Issue by mricaud** [jimetevenard/Maven-RelaxNG-Simplifier#4]
Hi @jimetevenard 

It would be great to be able to choose which version of jing one can use.
ELS company has forked jing (https://github.com/ELSGestion/jing-trang) and I would like to use this version  in your plugin (the one resolving https://github.com/ELSGestion/jing-trang/issues/6 actually).

I guess the project has to stick to jing implementation of RNG simplification, using any other implementation would become tricky here (unless an interface is provided) ?

**Comment by mricaud** [comment]
Hi @jimetevenard 
@jbvalentin worked on https://github.com/ELSGestion/jing-trang/issues/6
I would have like to test with your plugin, so if you have the opportunity to look at this issue about jing as dependency, that would be quite nice (other of my issues are less important)

**Comment by jimetevenard** [comment]
This is now fixed in Release 2.0.0
